### PR TITLE
Add `VIP_GO_ENV` constant

### LINKED ISSUE #53: Define VIP_GO_ENV constant
We should populate the VIP_GO_ENV with a value to flag this as the VIP Go Quickstart environment.

### PR DESCRIPTION
**Pull request by simonwheatley**
With an appropriate value for VIP Go Quickstart

Closes #53

### CODE REVIEW

**Comment by simonwheatley** [comment]
This change requires a `vagrant provision` to apply.

**Comment by simonwheatley** [comment]
https://github.com/Automattic/vip-go-quickstart/pull/54/commits/c6ae1e40d75cd2bd3f5839a66bb2c63d2a6b9dfc introduces a version check, which then conditionally runs `vagrant provision` if the version in `.git` (i.e. in `.version.txt`) is higher than the locally recorded version. 

Needs testing to check `vagrant provision` works correctly, see https://github.com/Automattic/vip-go-quickstart/issues/55

**Comment by joshbetz** [comment]
I wonder if we should add a wp-config that we can link into the main wp-config that we can update without provisioning.

Also, since `vagrant provision` is idempotent, I'd rather run it every time and avoid the logic that decides whether we should or should not run it.

**Comment by simonwheatley** [comment]
> Also, since `vagrant provision` is idempotent, I'd rather run it every time and avoid the logic that decides whether we should or should not run it.

Running `vagrant provision` adds 13 seconds to running the `qs-init.sh` script.

In the past, we've discussed the need for something like this (or similar) which allows us to transition users from one version of Quickstart to another, particularly where some migrations are required. That said, if we can avoid adding logic then we should.

Looking into adding that separate config file…

**Comment by simonwheatley** [comment]
https://github.com/Automattic/vip-go-quickstart/pull/54/commits/bbbadff7831d5eb9672602adab6669d9aab7e418 and https://github.com/Automattic/vip-go-quickstart/pull/54/commits/162dddd5ddf9e2a9b151145eb1a6869ca64f71ca add the config file

**Comment by simonwheatley** [comment]
If we're happy to optimise `vagrant provision` in a future iteration, then this PR is ready for review and merge, @joshbetz

**Pull request merged**
